### ISSUE TITLE
Mention in readme how to run commands

### ISSUE THREAD

**Issue by kamyker** [PlayFab/vscode-playfab-explorer#58]
Something like: right click on studio name to get list of commands

**Comment by MGudgin** [comment]
Thanks for bringing this up. I've created this [PR](https://github.com/PlayFab/vscode-playfab-explorer/pull/62) to address this issue.

**Comment by MGudgin** [comment]
The PR has been merged and a new version of the extension published to the marketplace. Closing this issue.
